### ISSUE TITLE
Add Iceberg Table Format as a table data source

### ISSUE THREAD

**Issue by ashvina** [onetable-io/onetable#7]
## Subtasks

- [x] Externalize OneTable client lists and configuration
- [x] Add interface for OneTable source client provider (factory)
- [x] Migrate HudiClient to source provider
- [x] #8
- [x] #10

**Comment by the-other-tim-brown** [comment]
Marking this as closed now that we have an Iceberg source and have tested it
